# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [11, 16, 17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: List files
      run: ls -R
    - name: Install BungeeChatApi locally
      run: |
        mvn install:install-file \
          -Dfile=core/bungeecord/BungeeChatApi-2.2.3.1241.jar \
          -DgroupId=dev.aura.bungeechat.api \
          -DartifactId=BungeeChatApi \
          -Dversion=2.2.3.1241 \
          -Dpackaging=jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
